### ISSUE TITLE
Make use of MDNS compatible with ZeroTier usage

### ISSUE THREAD

**Issue by Connoropolous** [holochain/n3h#100]
On lines: 
https://github.com/holochain/n3h/blob/16e42ffaa5c0c13e5917427ec056ebbb00ecf664/lib/n3h-mod-discovery-mdns/discovery-mdns.js#L38-L43

We need to pass value `interface`
https://github.com/mafintosh/multicast-dns/blame/master/README.md#L117
which should equal the IP address of the node on the ZeroTier network

Through hacking and testing, this is how I've managed to make MDNS work with ZeroTier.

Otherwise, each node defaults to binding to `0.0.0.0` and nodes don't seem to discover one another.

**Comment by Connoropolous** [comment]
I would propose it’s accomplished by adding a value to the config file with a sensible default. Inside the MDNS config block

**Comment by jmday** [comment]
It sounds like this is the next step for supporting mdns discovery via ZeroTier. @ddd-mtl Could you please prioritize this work as we discussed? If you have any concerns about this approach, I'm definitely interested in getting your thoughts here!
