### ISSUE TITLE
We're not converting the charErasures here into 1-2 trueErasures

### ISSUE THREAD

**Issue by pjkundert** [holochain/n3h#41]
https://github.com/holochain/n3h/blob/21d656d1569c27041092d30d005870ca3e618987/packages/hc-dpki/delete-me/hid.js#L94

Every charErasure detected in the payload of the Base-32 decode affects 5 bits, which can blur across 1-2 octets; these need to be computed, and one or both added to the trueErasures array.

Then, later in _capDecode, the same Base-32 erasure is, again, going to have an effect on an octet of caps-encoded parity. This could be optimized; if the erasure is *after* the 8 bits of parity data is collected, we could ignore it, as it won't affect the parity data.  Or, better yet, we return a tuple of "possible" parity data values; with the bit '1', '0', ignored as if it was a digit, and as a null (erasure) -- and the R-S decoder tries to decode with each permutation of the supplied options.  Probably not worth doing right now...

**Comment by neonphog** [comment]
handled in https://github.com/holochain/hcid
