### ISSUE TITLE
npm install: found 1 high severity vulnerability

### ISSUE THREAD

**Issue by mrbianchi** [holochain/n3h#64]
`                       === npm audit security report ===

# Run  npm install --save-dev nyc@13.3.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

  High            Prototype Pollution

  Package         handlebars

  Dependency of   nyc [dev]

  Path            nyc > istanbul-reports > handlebars

  More info       https://nodesecurity.io/advisories/755

found 1 high severity vulnerability in 3086 scanned packages
  1 vulnerability requires semver-major dependency updates.`

**Comment by mrbianchi** [comment]
UPDATE: 

`> node-gyp-build "node preinstall.js" "node postinstall.js"

added 678 packages from 1070 contributors and audited 3088 packages in 24.84s
found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details`

**Comment by neonphog** [comment]
resolved by https://github.com/holochain/n3h/pull/75
